/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Bot } from "./Bot";
import { BotCountArgs } from "./BotCountArgs";
import { BotFindManyArgs } from "./BotFindManyArgs";
import { BotFindUniqueArgs } from "./BotFindUniqueArgs";
import { CreateBotArgs } from "./CreateBotArgs";
import { UpdateBotArgs } from "./UpdateBotArgs";
import { DeleteBotArgs } from "./DeleteBotArgs";
import { User } from "../../user/base/User";
import { BotService } from "../bot.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Bot)
export class BotResolverBase {
  constructor(
    protected readonly service: BotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "any",
  })
  async _botsMeta(
    @graphql.Args() args: BotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Bot])
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "any",
  })
  async bots(@graphql.Args() args: BotFindManyArgs): Promise<Bot[]> {
    return this.service.bots(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Bot, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "own",
  })
  async bot(@graphql.Args() args: BotFindUniqueArgs): Promise<Bot | null> {
    const result = await this.service.bot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Bot)
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "create",
    possession: "any",
  })
  async createBot(@graphql.Args() args: CreateBotArgs): Promise<Bot> {
    return await this.service.createBot({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Bot)
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "update",
    possession: "any",
  })
  async updateBot(@graphql.Args() args: UpdateBotArgs): Promise<Bot | null> {
    try {
      return await this.service.updateBot({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Bot)
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "delete",
    possession: "any",
  })
  async deleteBot(@graphql.Args() args: DeleteBotArgs): Promise<Bot | null> {
    try {
      return await this.service.deleteBot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Bot): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
